### ISSUE TITLE
Logger not working compiled by visual studio compiler

### ISSUE THREAD

**Issue by mareu** [TRUEPADDii/TitanBlade3D#3]
**Steps to reproduce**
Run the Project from Visual Studio

**Actual result**
No logged informations are displayed in the console

**Expected result**
Logged informations should be visible in the console

**Comment by TRUEPADDii** [comment]
The reason for the whole _COMPILE_WITH_LOGS_ stuff was, that you can define this for debug mode and only then logs would be generated. Logging takes time, which we'd like to save in release mode. The CMake project file does contain a **/DCOMPILE_WITH_LOGS** flag but unfortunately it seems as if it is not working. So please check back whether we can solve this issue in CMake or let's talk about a better solution for logging in release mode.

**Comment by TRUEPADDii** [comment]
This issue has been resolved.
